### ISSUE TITLE
whats happen when user dont have whatsapp?

### ISSUE THREAD

**Issue by boynet** [ranjitpandit/whatsapp-phonegap-plugin#1]
can you make it default to work like tel: ?

**Comment by ranjitpandit** [comment]
If the user does not have whatsapp the plugin simply returns with errorCallback.

Here is an example:

``` javascript
if( cordova.plugins.Whatsapp) {
   cordova.plugins.Whatsapp.send(action.context.value,
   function(){
      console.log("whatsapp send success!");
   },
   function(){
       console.log("whatsapp send error!!");
   });
}
```

can you clarify what you mean by work like tel: ?

**Comment by boynet** [comment]
oh thanks

**Comment by purelydeft** [comment]
Hello Ranjit

First of all thanks for this amazing plugin, but each time install this plugin and run on my phonegap app, it shows the WhatsApp number you are trying to send msg to does not registered on whtsapp but I have tried with multiple numbers registered on whatsapp.

Can you please let me know, which one is the correct format of number to send whatsapp msg to?

Regards
Deftsoft Developer

**Comment by unaor** [comment]
Hiim not the dev of the plugin , im a user

```
  From: purelydeft <notifications@github.com>
```

 To: ranjitpandit/whatsapp-phonegap-plugin whatsapp-phonegap-plugin@noreply.github.com 
 Sent: Friday, July 24, 2015 6:18 AM
 Subject: Re: [whatsapp-phonegap-plugin] whats happen when user dont have whatsapp? (#1)

Hello RanjitFirst of all thanks for this amazing plugin, but each time install this plugin and run on my phonegap app, it shows the WhatsApp number you are trying to send msg to does not registered on whtsapp but I have tried with multiple numbers registered on whatsapp.Can you please let me know, which one is the correct format of number to send whatsapp msg to?Regards
Deftsoft Developer—

**Comment by NayHaPal** [comment]
WhatsApp number you are trying to send msg to does not registered on whtsapp but I have tried with multiple numbers registered on whatsapp. 

can you solve this problem !!? 
how we can pass this messages ?!
